# This is the Supabase configuration for local development

[auth]
# The base URL of your website
site_url = "http://localhost:3000"

# A list of URLs allowed for redirects
additional_redirect_urls = [
  "http://localhost:3000/**",
  "http://127.0.0.1:3000/**",
  "http://localhost:54321/auth/v1/callback",
  "http://localhost:3000/auth/callback"
]

# If enabled, the nonce check will be skipped. Required for local sign in with Google auth.
skip_nonce_check = true

# Configure Google OAuth provider
[auth.external.google]
enabled = true
client_id = "env(SUPABASE_AUTH_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_AUTH_GOOGLE_SECRET)"
redirect_uri = "http://localhost:54321/auth/v1/callback" 