import { NextResponse } from 'next/server';
import JSZip from 'jszip';
import { supabaseAdmin } from '@/lib/supaClient';

// In-memory cache for temporary download artifacts
// In production, this would be stored in a database or cloud storage
const downloadCache: Record<string, {
  expires: Date,
  serverFiles?: Record<string, string>,
  claudeConfig?: Record<string, string>,
  cursorConfig?: Record<string, string>,
  config?: any
}> = {};

// Store download data in cache
export async function storeDownloadData(id: string, data: any): Promise<void> {
  // Set expiration to 1 hour from now
  const expires = new Date();
  expires.setHours(expires.getHours() + 1);
  
  downloadCache[id] = {
    expires,
    ...data
  };
  
  // Clean up expired entries
  cleanupExpiredDownloads();
}

// Clean up expired entries
function cleanupExpiredDownloads(): void {
  const now = new Date();
  
  Object.keys(downloadCache).forEach(id => {
    if (downloadCache[id].expires < now) {
      delete downloadCache[id];
    }
  });
}

// Function to generate server.ts file (TypeScript)
function generateServerTs(config: any): string {
  const serverTemplate = `// MCP Server generated by buildmcp.space
import { createServer } from '@modelcontextprotocol/sdk';

// Define types for MCP components
interface MCPResource {
  id: string;
  name: string;
  description?: string;
  [key: string]: any;
}

interface MCPTool {
  id: string;
  name: string;
  description?: string;
  parameters?: any;
  [key: string]: any;
}

interface MCPPrompt {
  id: string;
  name: string;
  description?: string;
  text: string;
  [key: string]: any;
}

// MCP server configuration
const resources: MCPResource[] = ${JSON.stringify(config.resources || [], null, 2)};
const tools: MCPTool[] = ${JSON.stringify(config.tools || [], null, 2)};
const prompts: MCPPrompt[] = ${JSON.stringify(config.prompts || [], null, 2)};

const server = createServer({
  resources,
  tools,
  prompts,
  config: {
    name: "${config.metadata?.name || 'MCP Server'}",
    description: "${config.description || ''}"
  }
});

// Start the server
const PORT = process.env.PORT || 3333;
server.listen(PORT, () => {
  console.log(\`MCP Server running at http://localhost:\${PORT}\`);
});
`;

  return serverTemplate;
}

// Generate tsconfig.json
function generateTsConfig(): string {
  return JSON.stringify({
    "compilerOptions": {
      "target": "ES2020",
      "module": "commonjs",
      "esModuleInterop": true,
      "forceConsistentCasingInFileNames": true,
      "strict": true,
      "skipLibCheck": true,
      "outDir": "dist"
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules"]
  }, null, 2);
}

// Generate Claude Desktop config
function generateClaudeConfig(mcpId: string): string {
  const claudeConfig = {
    "mcpServers": {
      [`mcp-${mcpId.substring(0, 6)}`]: {
        "command": "node",
        "args": [
          "dist/server.js"
        ]
      }
    }
  };
  
  return JSON.stringify(claudeConfig, null, 2);
}

// Generate Cursor config
function generateCursorConfig(mcpId: string): string {
  const cursorConfig = {
    "mcpServers": {
      [`mcp-${mcpId.substring(0, 6)}`]: {
        "command": "node",
        "args": [
          "dist/server.js"
        ]
      }
    }
  };
  
  return JSON.stringify(cursorConfig, null, 2);
}

// Generate package.json with TypeScript dependencies
function generatePackageJson(mcpId: string): string {
  const packageJson = {
    "name": `mcp-server-${mcpId.substring(0, 6)}`,
    "version": "1.0.0",
    "description": "MCP Server generated by buildmcp.space",
    "main": "dist/server.js",
    "scripts": {
      "build": "tsc",
      "start": "node dist/server.js",
      "dev": "ts-node src/server.ts"
    },
    "dependencies": {
      "@modelcontextprotocol/sdk": "^1.0.0"
    },
    "devDependencies": {
      "@types/node": "^20.5.0",
      "typescript": "^5.1.6",
      "ts-node": "^10.9.1"
    }
  };
  
  return JSON.stringify(packageJson, null, 2);
}

// Generate README with instructions for TypeScript
function generateReadme(mcpId: string): string {
  return `# MCP Server (${mcpId.substring(0, 6)})

This MCP server was generated by buildmcp.space.

## Installation

1. Make sure you have Node.js installed (download from https://nodejs.org/)
2. Run \`npm install\` to install dependencies
3. Run \`npm run build\` to compile TypeScript to JavaScript
4. Run \`npm start\` to start the server

## Development

- Source files are in the \`src\` directory in TypeScript
- Use \`npm run dev\` to run the server in development mode
- Use \`npm run build\` to compile TypeScript to JavaScript

## Client Configuration

### Claude Desktop

1. Open Claude Desktop
2. Go to Settings > Servers
3. Add a new server with the following configuration:
   - Name: MCP Server (${mcpId.substring(0, 6)})
   - Path to server: Use the path to the running server
   - Alternatively, edit your Claude Desktop config to include the contents of \`claude_desktop_config.json\`

### Cursor

1. Create a \`.cursor\` directory in your project root (if it doesn't exist)
2. Copy \`mcp.json\` to the \`.cursor\` directory
3. Restart Cursor

## Files

- \`src/server.ts\`: The main server file (TypeScript source)
- \`dist/server.js\`: The compiled JavaScript file (generated after build)
- \`tsconfig.json\`: TypeScript configuration
- \`package.json\`: Node.js package configuration
- \`claude_desktop_config.json\`: Configuration for Claude Desktop
- \`mcp.json\`: Configuration for Cursor
- \`install.bat\`: Windows installation script
- \`install.sh\`: Mac/Linux installation script
`;
}

// Generate install scripts with TypeScript build step
function generateInstallScripts(): { windows: string, unix: string } {
  const windowsScript = `@echo off
echo Installing MCP Server dependencies...
npm install
echo.
echo Building TypeScript...
npm run build
echo.
echo Installation complete. To start the server, run:
echo npm start
pause
`;

  const unixScript = `#!/bin/bash
echo "Installing MCP Server dependencies..."
npm install
echo ""
echo "Building TypeScript..."
npm run build
echo ""
echo "Installation complete. To start the server, run:"
echo "npm start"
chmod +x install.sh
`;

  return { windows: windowsScript, unix: unixScript };
}

// GET /api/mcp/download/[id]/[type]
export async function GET(request: Request, { params }: { params: { id: string, type: string } }) {
  try {
    const { id, type } = params;
    
    // Check if download exists in cache
    if (!downloadCache[id]) {
      // Try to find in Supabase
      if (supabaseAdmin) {
        // First check if this is a deployment ID
        const { data: deploymentData, error: deploymentError } = await supabaseAdmin
          .from('mcp_deployments')
          .select('config, project_id')
          .eq('id', id)
          .single();
          
        if (deploymentError || !deploymentData) {
          // If not a deployment, try to find the MCP project directly
          const { data: mcpData, error: mcpError } = await supabaseAdmin
            .from('mcp_projects')
            .select('config, id')
            .eq('id', id)
            .single();
            
          if (mcpError || !mcpData) {
            console.error('MCP data not found in Supabase:', mcpError);
            return NextResponse.json({ error: 'MCP not found' }, { status: 404 });
          }
          
          // Store in cache using the MCP data directly
          await storeDownloadData(id, {
            config: mcpData.config,
            serverFiles: {
              'src/server.ts': generateServerTs(mcpData.config),
              'tsconfig.json': generateTsConfig(),
              'package.json': generatePackageJson(mcpData.id),
              'README.md': generateReadme(mcpData.id),
              'install.bat': generateInstallScripts().windows,
              'install.sh': generateInstallScripts().unix
            },
            claudeConfig: {
              'claude_desktop_config.json': generateClaudeConfig(mcpData.id)
            },
            cursorConfig: {
              'mcp.json': generateCursorConfig(mcpData.id)
            }
          });
        } else {
          // We found a deployment, get the associated MCP project
          const { data: mcpData, error: mcpError } = await supabaseAdmin
            .from('mcp_projects')
            .select('config')
            .eq('id', deploymentData.project_id)
            .single();
            
          if (mcpError || !mcpData) {
            return NextResponse.json({ error: 'MCP not found' }, { status: 404 });
          }
          
          // Store in cache
          await storeDownloadData(id, {
            config: mcpData.config,
            serverFiles: {
              'src/server.ts': generateServerTs(mcpData.config),
              'tsconfig.json': generateTsConfig(),
              'package.json': generatePackageJson(deploymentData.project_id),
              'README.md': generateReadme(deploymentData.project_id),
              'install.bat': generateInstallScripts().windows,
              'install.sh': generateInstallScripts().unix
            },
            claudeConfig: {
              'claude_desktop_config.json': generateClaudeConfig(deploymentData.project_id)
            },
            cursorConfig: {
              'mcp.json': generateCursorConfig(deploymentData.project_id)
            }
          });
        }
      } else {
        return NextResponse.json({ error: 'Download not available' }, { status: 404 });
      }
    }
    
    const downloadData = downloadCache[id];
    if (!downloadData) {
      return NextResponse.json({ error: 'Download not available' }, { status: 404 });
    }
    
    // Create a zip file based on the requested type
    const zip = new JSZip();
    
    switch (type) {
      case 'server':
        // Add server files
        if (downloadData.serverFiles) {
          Object.entries(downloadData.serverFiles).forEach(([filename, content]) => {
            // Create directories if filename contains path separators
            if (filename.includes('/')) {
              const parts = filename.split('/');
              const fileName = parts.pop() || '';
              
              // Create folder structure
              let currentFolder = zip;
              for (const dir of parts) {
                const folder = currentFolder.folder(dir);
                if (folder) {
                  currentFolder = folder;
                }
              }
              
              // Add file to the correct folder
              currentFolder.file(fileName, content);
            } else {
              zip.file(filename, content);
            }
          });
        }
        break;
        
      case 'claude':
        // Add Claude Desktop config
        if (downloadData.claudeConfig) {
          Object.entries(downloadData.claudeConfig).forEach(([filename, content]) => {
            zip.file(filename, content);
          });
        }
        break;
        
      case 'cursor':
        // Add Cursor config
        if (downloadData.cursorConfig) {
          Object.entries(downloadData.cursorConfig).forEach(([filename, content]) => {
            zip.file(filename, content);
          });
        }
        break;
        
      case 'bundle':
        // Add all files
        if (downloadData.serverFiles) {
          Object.entries(downloadData.serverFiles).forEach(([filename, content]) => {
            // Create directories if filename contains path separators
            if (filename.includes('/')) {
              const parts = filename.split('/');
              const fileName = parts.pop() || '';
              
              // Create folder structure
              let currentFolder = zip;
              for (const dir of parts) {
                const folder = currentFolder.folder(dir);
                if (folder) {
                  currentFolder = folder;
                }
              }
              
              // Add file to the correct folder
              currentFolder.file(fileName, content);
            } else {
              zip.file(filename, content);
            }
          });
        }
        
        if (downloadData.claudeConfig) {
          Object.entries(downloadData.claudeConfig).forEach(([filename, content]) => {
            zip.file(filename, content);
          });
        }
        
        if (downloadData.cursorConfig) {
          Object.entries(downloadData.cursorConfig).forEach(([filename, content]) => {
            zip.file(filename, content);
          });
        }
        break;
        
      default:
        return NextResponse.json({ error: 'Invalid download type' }, { status: 400 });
    }
    
    // Generate the zip file
    const zipContent = await zip.generateAsync({ type: 'nodebuffer' });
    
    // Prepare the response with appropriate headers
    const response = new NextResponse(zipContent);
    
    // Set headers
    response.headers.set('Content-Type', 'application/zip');
    response.headers.set('Content-Disposition', `attachment; filename="mcp-${type}-${id.substring(0, 6)}.zip"`);
    
    return response;
  } catch (error) {
    console.error('Error generating download:', error);
    return NextResponse.json({ error: 'Failed to generate download' }, { status: 500 });
  }
} 